# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24
# 

Name:       gst-plugins-bad-free

# >> macros
# << macros

Summary:    GStreamer streaming media framework bad-free plug-ins
Version:    0.10.21
Release:    1
Group:      Applications/Multimedia
License:    LGPLv2+ and LGPLv2
URL:        http://gstreamer.freedesktop.org/
Source0:    gst-plugins-bad-free-%{version}.tar.bz2
Source1:    gst-p-bad-cleanup.sh
Source100:  gst-plugins-bad-free.yaml
Patch0:     0002-Lower-gettext-requirement-from-0.17-to-0.13.patch
Patch1:     0003-camerabin-change-default-yuv-format-from-I420-to-UYV.patch
Patch2:     0004-camerabin-change-video-viewfinder-queue-to-be-leaky-.patch
Patch3:     0005-camerabin-change-queue-place-in-videobin-Maemo-speci.patch
Patch4:     0006-camerabin-add-performance-timestamping-Maemo-specifi.patch
Patch5:     0007-camerabin-set-only-image-color-conversion-flag-by-de.patch
Patch6:     0008-camerabin-update-v4l2camsrc-driver-name-to-v4l2camex.patch
Patch7:     0009-camerabin-improve-timestamping-for-viewfinder-Maemo-.patch
Patch8:     0010-GstPhotography-Added-operation-mode-to-photography-A.patch
Patch9:     0011-camerabin-photography-Add-autofocus-interface-proper.patch
Patch10:     0012-camerabin-fix-build-when-enable-timestamps-is-used-m.patch
Patch11:     0013-camerabin-limit-still-image-capture-frames-memory-us.patch
Patch12:     0014-camerabin-set-image-resolution-to-video-source-befor.patch
Patch13:     0015-camerabin-Take-account-sensor-mode-aspect-ratio-when.patch
Patch14:     0016-camerabin-handle-preview-image-from-video-source.patch
Patch15:     0017-camerabin-rounding-support-for-framerate-setting.patch
Patch16:     0018-camerabin-fix-timestamp-for-photo-capture-start-and-.patch
Patch17:     0019-camerabin-Set-format-to-allow-preallocation-of-buffe.patch
Patch18:     0020-camerabin-viewfinder-mode-setting-for-subdevsrc.patch
Patch19:     0021-camerabin-make-sure-that-preview-caps-is-properly-se.patch
Patch20:     0022-camerabin-Fix-leaked-caps-reference-in-preview_notif.patch
Patch21:     0023-camerabin-update-framerate-choosing-logic.patch
Patch22:     0100-extend-photography-iface.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xt)
BuildRequires:  pkgconfig(gstreamer-0.10)
BuildRequires:  pkgconfig(gstreamer-plugins-base-0.10)
BuildRequires:  pkgconfig(libexif)
BuildRequires:  check
BuildRequires:  gettext-devel
BuildRequires:  orc-devel >= 0.4.5

%description
GStreamer is a streaming media framework, based on graphs of elements which
operate on media data.

This package contains plug-ins that are not tested well enough, or the code
is not of good enough quality.


%package devel
Summary:    Development tools for GStreamer bad free plugins
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for the GStreamer media framework bad free plug-ins



%prep
%setup -q -n %{name}-%{version}

# 0002-Lower-gettext-requirement-from-0.17-to-0.13.patch
%patch0 -p1
# 0003-camerabin-change-default-yuv-format-from-I420-to-UYV.patch
%patch1 -p1
# 0004-camerabin-change-video-viewfinder-queue-to-be-leaky-.patch
%patch2 -p1
# 0005-camerabin-change-queue-place-in-videobin-Maemo-speci.patch
%patch3 -p1
# 0006-camerabin-add-performance-timestamping-Maemo-specifi.patch
%patch4 -p1
# 0007-camerabin-set-only-image-color-conversion-flag-by-de.patch
%patch5 -p1
# 0008-camerabin-update-v4l2camsrc-driver-name-to-v4l2camex.patch
%patch6 -p1
# 0009-camerabin-improve-timestamping-for-viewfinder-Maemo-.patch
%patch7 -p1
# 0010-GstPhotography-Added-operation-mode-to-photography-A.patch
%patch8 -p1
# 0011-camerabin-photography-Add-autofocus-interface-proper.patch
%patch9 -p1
# 0012-camerabin-fix-build-when-enable-timestamps-is-used-m.patch
%patch10 -p1
# 0013-camerabin-limit-still-image-capture-frames-memory-us.patch
%patch11 -p1
# 0014-camerabin-set-image-resolution-to-video-source-befor.patch
%patch12 -p1
# 0015-camerabin-Take-account-sensor-mode-aspect-ratio-when.patch
%patch13 -p1
# 0016-camerabin-handle-preview-image-from-video-source.patch
%patch14 -p1
# 0017-camerabin-rounding-support-for-framerate-setting.patch
%patch15 -p1
# 0018-camerabin-fix-timestamp-for-photo-capture-start-and-.patch
%patch16 -p1
# 0019-camerabin-Set-format-to-allow-preallocation-of-buffe.patch
%patch17 -p1
# 0020-camerabin-viewfinder-mode-setting-for-subdevsrc.patch
%patch18 -p1
# 0021-camerabin-make-sure-that-preview-caps-is-properly-se.patch
%patch19 -p1
# 0022-camerabin-Fix-leaked-caps-reference-in-preview_notif.patch
%patch20 -p1
# 0023-camerabin-update-framerate-choosing-logic.patch
%patch21 -p1
# 0100-extend-photography-iface.patch
%patch22 -p1
# >> setup
# << setup

%build
# >> build pre
export NOCONFIGURE=1
# << build pre

%reconfigure --disable-static \
    --with-package-name='MeeGo GStreamer Bad Free Plugins package' \
    --with-package-origin='http://www.meego.com' \
    --enable-experimental \
    --disable-gtk-doc \
    --disable-debug \
    --disable-nls \
    --enable-orc

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mv %{buildroot}/%{_libdir}/pkgconfig/gstreamer-plugins-bad-0.10.pc %{buildroot}/%{_libdir}/pkgconfig/gstreamer-plugins-bad-free-0.10.pc
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libgstbasevideo-0.10.so.*
%{_libdir}/libgstphotography-0.10.so.*
%{_libdir}/libgstsignalprocessor-0.10.so.*
%{_libdir}/libgstbasecamerabinsrc-0.10.so.*
#%{_libdir}/gstreamer-0.10/libgst*.so
%{_libdir}/gstreamer-0.10/libgstliveadder.so
%{_libdir}/gstreamer-0.10/libgstrtpmux.so
%{_libdir}/gstreamer-0.10/libgstdtmf.so
%{_libdir}/gstreamer-0.10/libgstsdpelem.so
%{_libdir}/gstreamer-0.10/libgstautoconvert.so
%{_libdir}/gstreamer-0.10/libgstcamerabin.so
%{_libdir}/gstreamer-0.10/libgstcamerabin2.so
%{_libdir}/gstreamer-0.10/libgsth264parse.so
%{_libdir}/gstreamer-0.10/libgstjpegformat.so
%{_libdir}/gstreamer-0.10/libgstrawparse.so
%{_libdir}/gstreamer-0.10/libgstqtmux.so
%{_libdir}/gstreamer-0.10/libgstaudioparsersbad.so
%{_libdir}/gstreamer-0.10/libgstshm.so
%{_libdir}/gstreamer-0.10/libgstvideomaxrate.so
%ifarch %{ix86}
%{_libdir}/gstreamer-0.10/libgstreal.so
%endif
#debugging plugin
%{_libdir}/gstreamer-0.10/libgstdebugutilsbad.so

# From extras
#%{_libdir}/gstreamer-0.10/libgstwildmidi.so
#%ifarch %{ix86}
#%{_libdir}/gstreamer-0.10/libgstvp8.so
#%endif
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libgstbasevideo-0.10.so
%{_libdir}/libgstphotography-0.10.so
%{_libdir}/libgstsignalprocessor-0.10.so
%{_libdir}/libgstbasecamerabinsrc-0.10.so
%{_includedir}/gstreamer-0.10/gst/interfaces/photography*
%{_includedir}/gstreamer-0.10/gst/basecamerabinsrc
%{_includedir}/gstreamer-0.10/gst/signalprocessor
%{_includedir}/gstreamer-0.10/gst/video
%{_libdir}/pkgconfig/gstreamer-plugins-bad-free-0.10.pc
# << files devel
